### ISSUE TITLE
Add Releasing Docs

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-php#108]
With the Function Frameworks, we're trying to uniformly document the release process for all repos.

This is usually done via a section in [CONTRIBUTING](https://github.com/GoogleCloudPlatform/functions-framework-php/blob/master/CONTRIBUTING.md).

From my understanding, this repo is auto-published to packageist using a GitHub webhook.

It's not clear how we cut a version. Is that done manually?

**Comment by bshaffer** [comment]
Yes, currently we just go to the "releases" tab and tag the appropriate semantically versioned release for the changes included in that version.
