### ISSUE TITLE
Structured logging is broken

### ISSUE THREAD

**Issue by matthewrobertson** [GoogleCloudPlatform/functions-framework-php#131]
It seems like this regressed when we migrated from the PHP dev server to PHP FPM.

**Comment by josephlewis42** [comment]
Is this only happening locally or is this a buildpack issue?

**Comment by josephlewis42** [comment]
Looks like the backing issue for this was fixed in the buildpacks for GCF rather than the FF: https://github.com/GoogleCloudPlatform/buildpacks/commit/5e7e063b3125dab51729a4cf6ae4cac8b3789b88
