### ISSUE TITLE
Task: Investigate build-template.yaml

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/functions-framework-php#2]
As far as I can tell, `build-template.yaml` represents a [knative build template](https://github.com/knative/build-templates), which has been deprecated. Should we remove this? Do we need to add support for [Tekton pipelines](https://github.com/tektoncd/pipeline) instead?

**Comment by grant** [comment]
This can be removed.

**Comment by bshaffer** [comment]
Should we support any equivalent? Do any of the other FFs do this?

**Comment by bshaffer** [comment]
We have removed this for now in #1
