### ISSUE TITLE
Question: Should we support PSR-7 HTTP Message?

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/functions-framework-php#23]
Currently we support `symfony/http-foundation`, but this library could be expanded to also support any [PSR-7 compatible](https://www.php-fig.org/psr/psr-7/) HTTP library.  The most popular one of which is [`guzzle/psr7`](https://github.com/guzzle/psr7). 

This has the additional benefit of still supporting `symfony/http-foundation` through the [PSR-7 bridge](https://symfony.com/doc/current/components/psr7.html). 

A few options here:

   1. Add support for PSR-7 and use inflection on the function to determine which request object to pass in
   2. Change the framework to require PSR-7 message requests and responses

In this library we should still need to be opinionated about which library is used to create the request. However, the user could potentially use a different PSR-7 library for the response if they'd like, which would be a big win for interoperability

**Comment by grant** [comment]
Sounds fine to me so long as this is not a breaking change.

**Comment by bshaffer** [comment]
It wouldn't **_have_** to be a breaking change, but since we are pre-1.0, a breaking change is OK, and now would be the time to do it.

For it to not be breaking, we'd need logic to inflect the function and pass in the expected class of the typehint. This would be fine, but would come at a cost to performance. It should be a small cost, but still, we wouldn't want it.

**Comment by dominikzogg** [comment]
I would suggest to allow both based on typehint.

```
use ...\ServerRequestInterface;

function helloWorld(ServerRequestInterface $request) {
}
```

**Comment by bshaffer** [comment]
In doing this we would need to choose an implementation for `PSR-7`.
The only suitable option here would be:

 -  [`guzzle/psr7`](https://github.com/guzzle/psr7/blob/master/src/Stream.php)
 -  Rolling our own lightweight `Request`/`ServerResponse`/`Stream` classes

**Comment by dominikzogg** [comment]
@bshaffer there is a benchmark done (a year ago, by the winner, hopefully its still accurate) and it seems to the that https://github.com/Nyholm/psr7 is the fastest implementation

**Comment by bshaffer** [comment]
I've added #28 for PSR-7 support (with use of the `guzzle/psr7) library. I removed support for `symfony/http-foundation`. I do not think there is an advantage in supporting both, but am happy to hear from anyone if this is not the case!

**Comment by bshaffer** [comment]
Thank you for the intel @dominikzogg! Out of all the 3rd party packages I found, the Guzzle PSR7 package is the best choice for this library because it has significantly more usage and community support.

**Comment by dominikzogg** [comment]
@bshaffer your welcome, i am fine with guzzle/psr7. Keep in mind, that guzzle is probably the most used http client within php. Means most of the downloads use only the client part implementation.

**Comment by grayside** [comment]
To make sure I'm following, we're using PSR-7 implementation and developers could choose to use symfony/http-foundation if they so choose. In addition to this change, we may want to add a sample showing how to do that? Certainly would help mitigate a b/c break.

**Comment by grayside** [comment]
Reason this can't be closed?

**Comment by bshaffer** [comment]
Nope! This is now supported!
