### ISSUE TITLE
Support CloudEvent objects

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework-php#27]
Currently the PHP FF doesn't fully support CloudEvents. It supports HTTP and legacy events.

https://github.com/GoogleCloudPlatform/functions-framework-php/blob/master/src/BackgroundFunctionWrapper.php#L31

Ideally a user could sent a CloudEvent via a HTTP POST request with `CE-` headers and those headers would be easily accessible in an object with user code.

Example from Node:
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/test/invoker.ts#L160

I know it's a bit harder with no PHP CloudEvent SDK, but ideally we should still be able to cURL a server with a PHP FF handler and see user-friendly values in the function's code.

---

I also asked the CNCF WG to create a PHP SDK repo, which has been created and needs to be defined here: https://github.com/cloudevents/sdk-php

**Comment by bshaffer** [comment]
@grant do you know who is working on the [PHP sdk for Cloud Events](https://github.com/cloudevents/sdk-php)? This would be a good library to incorporate if it's in progress.

**Comment by grant** [comment]
Right now we don't have anyone working on the SDK.

I'll be working with some interns on that, more comms coming via email soon.

**Comment by grant** [comment]
I've added more details in #29 which should give very concrete examples and clarity to this FR.

Will be working on the PHP SDK, but that will be tangential and not required.
