### ISSUE TITLE
Status Code, Headers are ignored from a PSR-7 response.

### ISSUE THREAD

**Issue by dominikzogg** [GoogleCloudPlatform/functions-framework-php#33]
i missing the correct status code and headers

```php
function handle(ServerRequestInterface $request): ResponseInterface
{
    return new Response(404, ['Content-Type' => 'application'], '{"error": "not found"}');
}
```

i get 200 as a status code and the content-type is missing

tested with the docker locally (build / run)

**Comment by bshaffer** [comment]
We have tests for this, and I just added some more in #56 and confirmed it works, so this is now fixed.

**Comment by dominikzogg** [comment]
@bshaffer works like a charm, thx
