### ISSUE TITLE
Update behavior for event vs cloudevent function signature type

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/functions-framework-php#49]
The new behavior will be as follows:

- The function framework will accept legacy events and convert to a `CloudEvent` type for both `event` and `cloudevent` function signature types
 - User-provided functions will be validated at runtime to ensure the folliowing:
   - The function accepts exactly one parameter argument
   - The argument must be `RequestInterface` if the function signature type is `http`
   - The argument must be `CloudEvent` if the function signature type is `event` or `cloudevent`
   - The framework will throw an exception if any of the above conditions fail.
- Use functions-framework-conformance tests to verify

**Comment by mtraver** [comment]
Sounds good to me. Thanks!

**Comment by bshaffer** [comment]
@mtraver how do we tell a legacy `event` from a `cloudevent`? Is it by the presence of the JSON `data` property?

**Comment by mtraver** [comment]
Here's how Python does it: https://github.com/GoogleCloudPlatform/functions-framework-python/blob/46d2149e665622ae7d95ad028b339722ff941136/src/functions_framework/__init__.py#L114

**Comment by grant** [comment]
Node is similar, checking the 4 headers.
https://github.com/GoogleCloudPlatform/functions-framework-nodejs/blob/master/src/cloudevents.ts#L28

Note, we should also check if `application/cloudevents+json` (although GCP just needs the headers)

**Comment by bshaffer** [comment]
@mtraver this is very helpful, thank you. A few things:

1. The python code you provided does not convert from `Event` to `CloudEvent`, which we've decided to do here. Is there a standard way of converting from `Event` to `CloudEvent`? 
2. We do not differ between a "structured" vs "binary" Cloud Event. Does that need to be added as well?

**Comment by mtraver** [comment]
Here are the binary and structured converters in Python:

* BinaryHTTPCloudEventConverter: https://sourcegraph.com/github.com/cloudevents/sdk-python@master/-/blob/cloudevents/sdk/converters/binary.py#L24
* UnmarshalBinary: https://sourcegraph.com/github.com/cloudevents/sdk-python@master/-/blob/cloudevents/sdk/event/base.py#L253

* JSONHTTPCloudEventConverter: https://sourcegraph.com/github.com/cloudevents/sdk-python@master/-/blob/cloudevents/sdk/converters/structured.py#L24
* UnmarshalJSON: https://sourcegraph.com/github.com/cloudevents/sdk-python@master/-/blob/cloudevents/sdk/event/base.py#L221

**Comment by bshaffer** [comment]
@mtraver  Do we need to support `data_base64`? I see that is a field supported in Python that we are not currently supporting in PHP

**Comment by bshaffer** [comment]
@mtraver also, in the links you provided, I'm not seeing support for the legacy event fields `resource`, `eventType`, `eventId`, or `timestamp`

**Comment by bshaffer** [comment]
Probably because `cloudevents` SDK doesn't cover legacy events, that should be handled in the functions framework...
