### ISSUE TITLE
Do we need to keep converter.go?

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/functions-framework-php#5]
in `builders/php/converter`, we have a `converter.go` file and a `Dockerfile`. These files are used in Google Cloud Functions to convert an application to a "Google Cloud Function".

It essentially just creates a container and adds the `google/cloud-functions-framework` dependency, and injects other variables using `build-template.yaml`.

Do we need any of this? Ideally the user would build from the Dockerfile that already exists as part of the dependency, which has already been downloaded. E.g:

```sh
cd my-app-dir
composer require google/cloud-functions-framework
docker build -t my-cloud-function -f vendor/google/cloud-functions-framework/Dockerfile .
docker run -p 8080:8080 -e FUNCTION_TARGET=helloHttp my-cloud-function
```

Is this sufficient for deploying to Cloud Run / GKE / etc?

**Comment by juliehockett** [comment]
A good reference for this would be to take a look at the Node.js and Go FFs -- the converter piece is done separately (internally at the moment), and the open source repo just contains the package. In the README, however, they lay out how you would create the relevant docker image and app. It would probably be useful to at least start with the same pattern, so that they're at least in sync.

**Comment by bshaffer** [comment]
Thank you @juliehockett ! That's more or less what I was looking for - confirmation that these are two separate things, one specifically for deploying to GCF and the other for deploying to a container environment. 

We can keep the `build-template.yaml` and contents of `builders/php/` if there's a way to use it externally (e.g. Cloud Build), but I can't figure it out.

**Comment by juliehockett** [comment]
I'd say keep whatever would be useful for examples, but not much more, in the interests of keeping it clean and simple.

**Comment by bshaffer** [comment]
We removed `converter.go` and the world has continued to turn, so I feel good about closing this. Thanks for your help Julie!
