### ISSUE TITLE
What should the composer package name be?

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/functions-framework-php#6]
Possible Package Names:

 * `google/cloud-functions-framework`
 * `google/gcf`
 * `google/gcf-framework`
 * `google/functions-framework`
 * Other

**Comment by bshaffer** [comment]
I prefer `google/cloud-functions-framework` as it's consistent with our other package names (e.g. `google/cloud-storage` and it's explicit.

**Comment by grant** [comment]
I didn't realize this package was not published (trying to run the hello world).
Can we publish this?
https://packagist.org/packages/google/cloud-functions-framework

**Comment by bshaffer** [comment]
fixed in #1 - `google/cloud-functions-framework`
