### ISSUE TITLE
CloudEvent function invocation is broken

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/functions-framework-php#65]
The following code sample (with a Firebase RTDB trigger) **pasted in the Console**...

```
<?php

use Google\CloudFunctions\CloudEvent;

$log = fopen('php://stderr', 'wb');

function hello_rtdb(CloudEvent $cloudevent)
{
    global $log;
    fwrite($log, sprintf('Function triggered by change to: %s' . PHP_EOL, $cloudevent->getSource()));
    fwrite($log, var_export($cloudevent->getData(), true) . PHP_EOL);
}
```

...triggers the following `TypeError`:
```
Uncaught TypeError: Argument 1 passed to hello_rtdb() must be an instance of Google\CloudFunctions\CloudEvent, array given in /workspace/index.php:7
Stack trace:
#0 [internal function]: hello_rtdb(Array, Object(Google\CloudFunctions\Context))
#1 /workspace/vendor/google/cloud-functions-framework/src/BackgroundFunctionWrapper.php(53): call_user_func('hello_rtdb', Array, Object(Google\CloudFunctions\Context))
#2 /workspace/vendor/google/cloud-functions-framework/src/Invoker.php(55): Google\CloudFunctions\BackgroundFunctionWrapper->execute(Object(GuzzleHttp\Psr7\ServerRequest))
#3 /workspace/vendor/google/cloud-functions-framework/router.php(75): Google\CloudFunctions\Invoker->handle()
#4 /workspace/vendor/google/cloud-functions-framework/router.php(77): {closure}()
#5 {main}
  thrown in /workspace/index.php on line 7
```

I suspect this is due to a typing issue in the PHP FF - maybe in [this method](https://github.com/GoogleCloudPlatform/functions-framework-php/blob/c01a77feff68a5522207e890a9d91b330fe2de7e/src/CloudEvent.php#L101)?

**Comment by ace-n** [comment]
**N.B:** this function _does_ run (on Cloud Functions itself) if I change the `CloudEvent` argument type to be an `array`.

**Comment by ace-n** [comment]
More info - looks like the function works when deployed via `DeployTest`...perhaps this a console-specific issue and/or it's using an out-of-date FF version?

cc @emesx

**Comment by bshaffer** [comment]
We've removed the `BackgroundFunctionWrapper` as of `v0.6`, and we are now on `v0.7.1.`, so this is definitely an issue with an outdated FF version.
