### ISSUE TITLE
Feature Request: Enable grpc extension by default

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/functions-framework-php#70]
Some of our client libraries (Firestore, Redis and Spanner) require the `grpc` PHP extension. Users have to include a `php.ini` file to enable the extension. Additionally many APIs (such as Speech) use gRPC streaming calls which also require the extension.

We should enable grpc by default. This provides more performant API calls, streaming calls, and does not block certain client libraries.

**Comment by grayside** [comment]
This seems like it should be done in the buildpack, rather than in the framework.

**Comment by josephlewis42** [comment]
Closing this due to the previous comment by Adam. If this is something that's still needed, let's redirect it to the buildpacks repo.
