### ISSUE TITLE
feature request: PubSub Message Data should be easier to retrieve

### ISSUE THREAD

**Issue by bshaffer** [GoogleCloudPlatform/functions-framework-php#79]
This is pretty user-unfriendly....

```php
function myPubSubEvent(CloudEvent $event)
{
    $cloudEventData = $event->getData();
    $pubSubData = $cloudEventData['message']['data'];

    if ($pubSubData) {
        $name = htmlspecialchars(base64_decode($pubSubData));
    }
}
```

It's so user-unfriendly that our [own samples had it wrong](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1340/files).

Why not have something like `getMessageData`? We could make it a wrapper class `PubSubCloudEvent`, so it would not interfere with other cloud events, and the functions framework can check the event type, and send in a PubSubCloudEvent for those event types:

```php
function myPubSubEvent(PubSubEvent $event)
{
     $data = $event->getMessageData();
     $name = htmlspecialchars($data);
}
```

Another option is to just have `getMessageData` as a method on `CloudEvent`, which throws an exception if it doesn't exist.

**Comment by grayside** [comment]
I'm in favor of a helper like this. It does seem like something that could live here or in github.com/googleapis/google-cloudevents-php @grant

**Comment by grant** [comment]
Yes, the interface and devX should be better here.

The core interfaces we expose are HTTP and CloudEvents. CloudEvents have 9 attributes, one being the CloudEvent `data`. Pub/Sub happens to have a `data` property too (with `attributes`, `messageId`, `publishTime`).

I'd imagine the interface to be something like this:

```php
use Google\Cloud\Events\Cloud\Pubsub\V1; // need to create this

function myPubSubEvent(CloudEvent $ce)
{
    $ceData = new MessagePublishedData($ce->getData());
    $pubSubData = $ceData->getMessage()->getData();

    if ($pubSubData) {
        $name = htmlspecialchars(base64_decode($pubSubData));
    }
}
```

We have this repo, but don't have any contents:

https://github.com/googleapis/google-cloudevents-php

We'd need someone to add the contents / a prototype there. We don't have any contents there. We also don't have a types generator for the PHP language (as opposed to other languages).

**Comment by bshaffer** [comment]
That is an improvement, as it adds type safety, but from a dev-ex standpoint it isn't any better.

1. `message` is the only attribute of the array `$ce->getData()`
2. The string in `message.data` can always be base64 decoded, even when it's empty

Something like this could also work:

```php
use Google\CloudFunctions\Helpers\pubsub_data; // need to create this
use Google\CloudFunctions\Helpers\pubsub_attributes; // not really necessary but would be nice for consistency

function myPubSubEvent(CloudEvent $event)
{
    $pubSubData = pubsub_data($event);
    $attributes = pubsub_attributes($event);

    $name = $pubSubData ? htmlspecialchars($pubSubData) : 'Default';
}
```

**Comment by grayside** [comment]
I'm working on something in this space, still a bit early but happy to discuss.

**Comment by josephlewis42** [comment]
I'm going to close this in FF since I don't think FF is the right place to be putting CloudEvent helper functions. I agree that the Pub/Sub [UX isn't great](https://github.com/googleapis/google-cloudevents/blob/main/proto/google/events/cloud/pubsub/v1/data.proto), but it is the way they designed the interface and I'd rather lean on something that's more broadly agreed upon than creating one-offs in FF where we'd potentially have to chase upstream changes.
